// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RezSaaS.Modules.Messaging.Infrastructure.Persistence;

#nullable disable

namespace RezSaaS.Modules.Messaging.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MessagingDbContext))]
    [Migration("20260604175102_AddPlatformTransactionalMessages")]
    partial class AddPlatformTransactionalMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("messaging")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RezSaaS.Modules.Messaging.Domain.PlatformTransactionalMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryKey")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryKey")
                        .IsUnique();

                    b.HasIndex("Purpose", "CorrelationId");

                    b.HasIndex("Status", "NextAttemptAtUtc", "CreatedAtUtc");

                    b.ToTable("PlatformTransactionalMessages", "messaging", t =>
                        {
                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_AttemptAfterCreation", "\"LastAttemptAtUtc\" IS NULL OR \"LastAttemptAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_AttemptCount", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_CompletionAfterCreation", "\"CompletedAtUtc\" IS NULL OR \"CompletedAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_DeliveryAfterCreation", "\"SentAtUtc\" IS NULL OR \"SentAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_LockAfterAttempt", "\"LockedUntilUtc\" IS NULL OR (\"LastAttemptAtUtc\" IS NOT NULL AND \"LockedUntilUtc\" > \"LastAttemptAtUtc\")");

                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_NextAttemptAfterCreation", "\"NextAttemptAtUtc\" IS NULL OR \"NextAttemptAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_SentShape", "\"Status\" <> 'Sent' OR \"SentAtUtc\" IS NOT NULL");

                            t.HasCheckConstraint("CK_PlatformTransactionalMessages_StateShape", "(\"Status\" = 'Pending'\n    AND \"NextAttemptAtUtc\" IS NOT NULL\n    AND \"LockedUntilUtc\" IS NULL\n    AND \"CompletedAtUtc\" IS NULL)\nOR\n(\"Status\" = 'Processing'\n    AND \"NextAttemptAtUtc\" IS NULL\n    AND \"LockedUntilUtc\" IS NOT NULL\n    AND \"CompletedAtUtc\" IS NULL)\nOR\n(\"Status\" IN ('Sent', 'Failed', 'Cancelled')\n    AND \"NextAttemptAtUtc\" IS NULL\n    AND \"LockedUntilUtc\" IS NULL\n    AND \"CompletedAtUtc\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RezSaaS.Modules.Messaging.Domain.TransactionalMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProviderMessageId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RecipientMasked")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("TransactionalMessages", "messaging");
                });
#pragma warning restore 612, 618
        }
    }
}
