// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RezSaaS.Modules.Integrations.Infrastructure.Persistence;

#nullable disable

namespace RezSaaS.Modules.Integrations.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntegrationsDbContext))]
    partial class IntegrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("integrations")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RezSaaS.Modules.Integrations.Domain.IntegrationApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("KeyHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RevocationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeSet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeyHashSha256")
                        .IsUnique();

                    b.HasIndex("TenantId", "KeyPrefix")
                        .IsUnique();

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("IntegrationApiClients", "integrations", t =>
                        {
                            t.HasCheckConstraint("CK_IntegrationApiClients_KeyHashSha256", "length(\"KeyHashSha256\") = 64");

                            t.HasCheckConstraint("CK_IntegrationApiClients_RevocationShape", "(\"Status\" = 'Active'\n    AND \"RevokedByUserAccountId\" IS NULL\n    AND \"RevokedAtUtc\" IS NULL\n    AND length(\"RevocationReason\") = 0)\nOR\n(\"Status\" = 'Revoked'\n    AND \"RevokedByUserAccountId\" IS NOT NULL\n    AND \"RevokedAtUtc\" IS NOT NULL\n    AND length(\"RevocationReason\") > 0)");
                        });
                });

            modelBuilder.Entity("RezSaaS.Modules.Integrations.Domain.IntegrationAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ActorUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAtUtc");

                    b.ToTable("IntegrationAuditLogEntries", "integrations");
                });

            modelBuilder.Entity("RezSaaS.Modules.Integrations.Domain.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAtUtc");

                    b.HasIndex("TenantId", "CorrelationId", "EventType");

                    b.HasIndex("TenantId", "SubscriptionId", "Status");

                    b.ToTable("WebhookDeliveries", "integrations", t =>
                        {
                            t.HasCheckConstraint("CK_WebhookDeliveries_AttemptCount", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_WebhookDeliveries_DeliveredAfterCreation", "\"DeliveredAtUtc\" IS NULL OR \"DeliveredAtUtc\" >= \"CreatedAtUtc\"");

                            t.HasCheckConstraint("CK_WebhookDeliveries_LockShape", "\"LockedUntilUtc\" IS NULL OR (\"LastAttemptAtUtc\" IS NOT NULL AND \"LockedUntilUtc\" > \"LastAttemptAtUtc\")");

                            t.HasCheckConstraint("CK_WebhookDeliveries_PayloadSha256", "length(\"PayloadSha256\") = 64");
                        });
                });

            modelBuilder.Entity("RezSaaS.Modules.Integrations.Domain.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RevocationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("SigningSecretHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "TargetUrl");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("WebhookSubscriptions", "integrations", t =>
                        {
                            t.HasCheckConstraint("CK_WebhookSubscriptions_RevocationShape", "(\"Status\" IN ('Active', 'Paused')\n    AND \"RevokedByUserAccountId\" IS NULL\n    AND \"RevokedAtUtc\" IS NULL\n    AND length(\"RevocationReason\") = 0)\nOR\n(\"Status\" = 'Revoked'\n    AND \"RevokedByUserAccountId\" IS NOT NULL\n    AND \"RevokedAtUtc\" IS NOT NULL\n    AND length(\"RevocationReason\") > 0)");

                            t.HasCheckConstraint("CK_WebhookSubscriptions_SigningSecretHashSha256", "length(\"SigningSecretHashSha256\") = 64");

                            t.HasCheckConstraint("CK_WebhookSubscriptions_TargetHttps", "\"TargetUrl\" LIKE 'https://%'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
