// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RezSaaS.Modules.Admin.Infrastructure.Persistence;

#nullable disable

namespace RezSaaS.Modules.Admin.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260604174833_AddClosureNoticeDelivery")]
    partial class AddClosureNoticeDelivery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("admin")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.AbuseAppeal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "Status", "CreatedAtUtc");

                    b.HasIndex("UserAccountId", "TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("AbuseAppeals", "admin", t =>
                        {
                            t.HasCheckConstraint("CK_AbuseAppeals_ReviewShape", "(\"Status\" = 'PendingReview'\n    AND \"ReviewedAtUtc\" IS NULL\n    AND \"ReviewedByUserAccountId\" IS NULL\n    AND \"ReviewReason\" IS NULL)\nOR\n(\"Status\" IN ('Accepted', 'Rejected')\n    AND \"ReviewedAtUtc\" IS NOT NULL\n    AND \"ReviewedAtUtc\" >= \"CreatedAtUtc\"\n    AND \"ReviewedByUserAccountId\" IS NOT NULL\n    AND \"ReviewReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.AbuseEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAtUtc");

                    b.HasIndex("UserAccountId", "OccurredAtUtc");

                    b.ToTable("AbuseEvents", "admin");
                });

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.AccountClosureCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerNotice")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("CustomerNoticeDeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("EligibleForExecutionAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExecutedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExecutionStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ExecutionStartedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("InternalReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("ProposedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProposedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReviewedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('PendingApproval', 'Approved', 'Executing')");

                    b.HasIndex("Status", "EligibleForExecutionAtUtc");

                    b.HasIndex("UserAccountId", "Status", "ProposedAtUtc");

                    b.ToTable("AccountClosureCases", "admin", t =>
                        {
                            t.HasCheckConstraint("CK_AccountClosureCases_CompletionAfterExecutionStart", "\"ExecutedAtUtc\" IS NULL OR \"ExecutedAtUtc\" >= \"ExecutionStartedAtUtc\"");

                            t.HasCheckConstraint("CK_AccountClosureCases_DecisionAfterProposal", "\"DecidedAtUtc\" IS NULL OR \"DecidedAtUtc\" >= \"ProposedAtUtc\"");

                            t.HasCheckConstraint("CK_AccountClosureCases_DecisionShape", "(\"Status\" = 'PendingApproval'\n    AND \"ReviewedByUserAccountId\" IS NULL\n    AND \"DecisionReason\" IS NULL\n    AND \"DecidedAtUtc\" IS NULL)\nOR\n(\"Status\" IN ('Approved', 'Rejected', 'CancelledByAppeal', 'Executing', 'Executed')\n    AND \"ReviewedByUserAccountId\" IS NOT NULL\n    AND \"DecisionReason\" IS NOT NULL\n    AND \"DecidedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_AccountClosureCases_ExecutionAfterEligibility", "\"ExecutionStartedAtUtc\" IS NULL\nOR\n(\"EligibleForExecutionAtUtc\" IS NOT NULL\n    AND \"ExecutionStartedAtUtc\" >= \"EligibleForExecutionAtUtc\")");

                            t.HasCheckConstraint("CK_AccountClosureCases_ExecutionShape", "(\"Status\" NOT IN ('Executing', 'Executed')\n    AND \"ExecutionStartedByUserAccountId\" IS NULL\n    AND \"ExecutionStartedAtUtc\" IS NULL\n    AND \"ExecutedByUserAccountId\" IS NULL\n    AND \"ExecutedAtUtc\" IS NULL)\nOR\n(\"Status\" = 'Executing'\n    AND \"ExecutionStartedByUserAccountId\" IS NOT NULL\n    AND \"ExecutionStartedAtUtc\" IS NOT NULL\n    AND \"ExecutedByUserAccountId\" IS NULL\n    AND \"ExecutedAtUtc\" IS NULL)\nOR\n(\"Status\" = 'Executed'\n    AND \"ExecutionStartedByUserAccountId\" IS NOT NULL\n    AND \"ExecutionStartedAtUtc\" IS NOT NULL\n    AND \"ExecutedByUserAccountId\" IS NOT NULL\n    AND \"ExecutedAtUtc\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_AccountClosureCases_NoSelfProposal", "\"UserAccountId\" <> \"ProposedByUserAccountId\"");

                            t.HasCheckConstraint("CK_AccountClosureCases_NoticeDeliveryShape", "(\"CustomerNoticeDeliveredAtUtc\" IS NULL\n    AND \"EligibleForExecutionAtUtc\" IS NULL)\nOR\n(\"CustomerNoticeDeliveredAtUtc\" IS NOT NULL\n    AND \"CustomerNoticeDeliveredAtUtc\" >= \"ProposedAtUtc\"\n    AND \"EligibleForExecutionAtUtc\" > \"CustomerNoticeDeliveredAtUtc\")");
                        });
                });

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.AdminAuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ActorUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserAccountId", "OccurredAtUtc");

                    b.ToTable("AdminAuditLogEntries", "admin");
                });

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.BusinessAbuseReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppointmentRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("ReportedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReportedUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserAccountId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "AppointmentRequestId")
                        .IsUnique();

                    b.HasIndex("TenantId", "ReportedByUserAccountId", "CreatedAtUtc");

                    b.HasIndex("TenantId", "Status", "CreatedAtUtc");

                    b.ToTable("BusinessAbuseReports", "admin", t =>
                        {
                            t.HasCheckConstraint("CK_BusinessAbuseReports_NoSelfReport", "\"ReportedUserAccountId\" <> \"ReportedByUserAccountId\"");

                            t.HasCheckConstraint("CK_BusinessAbuseReports_ReviewShape", "(\"Status\" = 'PendingReview'\n    AND \"ReviewedAtUtc\" IS NULL\n    AND \"ReviewedByUserAccountId\" IS NULL\n    AND \"ReviewReason\" IS NULL)\nOR\n(\"Status\" IN ('Confirmed', 'Dismissed')\n    AND \"ReviewedAtUtc\" IS NOT NULL\n    AND \"ReviewedAtUtc\" >= \"CreatedAtUtc\"\n    AND \"ReviewedByUserAccountId\" IS NOT NULL\n    AND \"ReviewReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.UserSanction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId", "StartsAtUtc");

                    b.ToTable("UserSanctions", "admin");
                });

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.UserStrike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IssuedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedByUserAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceAbuseReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceAbuseReportId")
                        .IsUnique();

                    b.HasIndex("UserAccountId", "ExpiresAtUtc");

                    b.HasIndex("UserAccountId", "IssuedAtUtc");

                    b.ToTable("UserStrikes", "admin", t =>
                        {
                            t.HasCheckConstraint("CK_UserStrikes_ExpiryAfterIssue", "\"ExpiresAtUtc\" > \"IssuedAtUtc\"");

                            t.HasCheckConstraint("CK_UserStrikes_RevocationAfterIssue", "\"RevokedAtUtc\" IS NULL OR \"RevokedAtUtc\" >= \"IssuedAtUtc\"");

                            t.HasCheckConstraint("CK_UserStrikes_RevocationShape", "(\"RevokedAtUtc\" IS NULL\n    AND \"RevokedByUserAccountId\" IS NULL\n    AND \"RevocationReason\" IS NULL)\nOR\n(\"RevokedAtUtc\" IS NOT NULL\n    AND \"RevokedByUserAccountId\" IS NOT NULL\n    AND \"RevocationReason\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("RezSaaS.Modules.Admin.Domain.UserStrike", b =>
                {
                    b.HasOne("RezSaaS.Modules.Admin.Domain.BusinessAbuseReport", null)
                        .WithMany()
                        .HasForeignKey("SourceAbuseReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
